# Generated by Django 4.2.27 on 2026-01-14 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('stored_name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=512)),
                ('size', models.BigIntegerField(default=0)),
                ('comment', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('public_token', models.CharField(db_index=True, default='', max_length=64, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
